create table if not exists public.client_chat_message_attachments (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.client_chat_messages(id) on delete cascade,
  attachment_name text not null,
  attachment_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists client_chat_message_attachments_message_id_idx
  on public.client_chat_message_attachments (message_id, sort_order);
